- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
    - name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
    - name: nginx
      state: started
      enable: yes

  #- name: 
   # ansible.builtin.